development:
  cloud_name: shirongfoo
  api_key: '563746632919917'
  api_secret: aZ1zfP05JjA_Dqk9TRDAHpvaVT0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: shirongfoo
  api_key: '563746632919917'
  api_secret: aZ1zfP05JjA_Dqk9TRDAHpvaVT0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: shirongfoo
  api_key: '563746632919917'
  api_secret: aZ1zfP05JjA_Dqk9TRDAHpvaVT0
  enhance_image_tag: true
  static_image_support: false
