# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eac0d77c9c2b3066213965d2cc2f679dedd808ed6effab4f059927fe5fc100ab7532fac91ea3554fdcbeb87d163dfc60cfe1a283c0e49d9fc2468f252cf1c461
  stripe_publishable_key: pk_test_8FXfLgyONyHPEgPMU1yeqemY
  stripe_secret_key: sk_test_tREmFFnBhZAgUgzPzESKmFOZ
  stripe_client_id: ca_AYW9XLeJxXqxKRV6pPfxXmmgXrudMvuj
  fee_percentage: 0

test:
  secret_key_base: 577a3f3e881a4c122be11897884c8e06f08e4170470de8b11980e013ac3080641ac0aacf0594dc3658ecf7cf20f30ee7a03567fc5fda4b04a6fda38a120cda69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: pk_test_8FXfLgyONyHPEgPMU1yeqemY
  stripe_secret_key: sk_test_tREmFFnBhZAgUgzPzESKmFOZ
  stripe_client_id: ca_AYW9XLeJxXqxKRV6pPfxXmmgXrudMvuj
  fee_percentage: 0
